version: '1.0.0'

services:

  registry:
    build: ./registry
    container_name: registry-container
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]

  gateway:
    build: ./gateway
    container_name: gateway-container
    ports:
      - "8888:8888"
    environment:
      EUREKA_URL: http://registry:8761/eureka/
    depends_on:
      registry:
        condition: service_healthy
      config:
        condition: service_healthy
      
  config:
    build: ./config
    container_name: config-container
    ports:
      - "9999:9999"
    environment:
      EUREKA_URL: http://registry:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
    depends_on:
      registry:
        condition: service_healthy
  
  
  ebank-client:
    build: ./ebank-client
    container_name: ebankclient-container
    ports:
      - "8081:8081"
    environment:
      CONFIG_URL: http://config:9999
      EUREKA_URL: http://registry:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://ebank-postgres:5432/ebankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - ebank-postgres
      - registry
      - config
      
  ebank-compte:
    build: ./ebank-compte
    container_name: ebankcompte-container
    ports:
      - "8082:8082"
    environment:
      CONFIG_URL: http://config:9999
      EUREKA_URL: http://registry:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://ebank-postgres:5432/ebankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - ebank-postgres
      - registry
      - config

  ebank-postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ebankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    ports:
      - "9090:9090"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 9090