version: '1.0.0'

services:

  registry:
    build: ./registry
    container_name: registry-container
    ports:
      - "8761:8761"

  gateway:
    build: ./gateway
    container_name: gateway-container
    ports:
      - "8888:8888"
    environment:
      EUREKA_URL: http://registry:8761/eureka/
    depends_on:
      - registry
      - config
      
  config:
    build: ./config
    container_name: config-container
    ports:
      - "9999:9999"
    environment:
      EUREKA_URL: http://registry:8761/eureka/
    depends_on:
      - registry
  
  ebank-client:
    build: ./ebank-client
    container_name: ebankclient-container
    ports:
      - "8081:8081"
    environment:
      CONFIG_URL: optional:configserver:http://config:9999
      EUREKA_URL: http://registry:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://ebank-postgres:5432/ebankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - registry
      - ebank-postgres
      - config

  ebank-postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ebankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root